#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Monir\AmsRouter\Command\AmsServe;
use Symfony\Component\Console\Application;
use App\Command\AmsCommand;

$application = new Application();

// Register commands
$application->add(new AmsServe());

$application->run();
